name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker login (harbor)
        uses: docker/login-action@v1
        with:
          username: robot-goreleaser+github-actions
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.fylr.io

      - name: docker login (new registry)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.FYLR_DOCKER_REGISTRY_2_LOGIN }}
          password: ${{ secrets.FYLR_DOCKER_REGISTRY_2_PASSWORD }}
          registry: docker-push.fylr.io

      - name: Extract tag version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Build docker image
        run: make build

      - name: Upload docker image
        run: make push

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          draft: true
          generate_release_notes: true
          files: |
            README.md
