name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.fylr.io
          username: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_USERNAME }}

      - name: Extract tag version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Build docker image
        run: make build

      - name: Upload docker image
        run: make upload

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          draft: true
          generate_release_notes: true
          files: |
            README.md